### PR TITLE
Add assist player

### PR DESCRIPTION
**Pull request by LarchLiu**
Add assist player to game_events.

https://github.com/dcaribou/transfermarkt-scraper/pull/71

### CODE REVIEW

**Comment by dcaribou** [comment]
Hey @LarchLiu,

I think you also need to upgrade the `transfermarkt-scraper` depedency, so the latest changes you made are available. You can do so by running
```console
poetry update transfermarkt-scraper
```
that should update the poetry.lock file, with the latest scraper changes.

Also, you'd ideally want to run the dbt project as well with the new data and ensure it works as you expect. I've recently added a template for codespaces, so it should be quite easy to spin up a dev environement (just click [here](https://codespaces.new/dcaribou/transfermarkt-datasets/tree/master?quickstart=1)).

Once the codespace has started, all you need to do is
1. Activate the poetry environment → Run command `poetry shell`
2. Initialise the data directory → Run command `dvc pull`
3. Run the scraper → Run command `make acquire_local ARGS="--asset games --season 2023"`
4. Run the dbt project → Run command `make prepare_local`

**Comment by dcaribou** [comment]
Ah, nice.

Then all that's missing then is the dependency upgrade then I think.
```console
poetry update transfermarkt-scraper
```

**Comment by LarchLiu** [comment]
Sorry, I'm not familiar with python and poetry. Pls check if the lock file is correct.

**Comment by dcaribou** [comment]
No problem 😄 

I think you somehow got way more changes than necessary. All it's needed is this change
image

This basically tells poetry to use the latest commit from the master branch in `transfermarkt-scraper`.
You can remove everything else.

**Pull request merged**
